# Generated by Django 4.1.7 on 2023-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(db_column='account_ID', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='Email', max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(db_column='UserName', max_length=50)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookedcab',
            fields=[
                ('bookedcab_id', models.IntegerField(db_column='Bookedcab_ID', primary_key=True, serialize=False)),
                ('drop_time', models.TimeField(db_column='Drop_time')),
                ('pickup_time', models.TimeField(db_column='Pickup_time')),
            ],
            options={
                'db_table': 'bookedcab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('cab_id', models.IntegerField(db_column='Cab_ID', primary_key=True, serialize=False)),
                ('owner_name', models.CharField(db_column='Owner_name', max_length=100)),
                ('number_plate', models.CharField(db_column='Number_plate', max_length=100)),
                ('model', models.CharField(db_column='Model', max_length=45)),
                ('cab_location', models.CharField(db_column='Cab_location', max_length=100)),
                ('pickup', models.CharField(db_column='Pickup', max_length=150)),
                ('destination', models.CharField(db_column='Destination', max_length=150)),
            ],
            options={
                'db_table': 'cab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.IntegerField(db_column='card_ID', primary_key=True, serialize=False)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('expiry', models.DateField(db_column='Expiry')),
                ('cvv', models.IntegerField(db_column='CVV')),
                ('holders_name', models.CharField(db_column='Holders_name', max_length=50)),
            ],
            options={
                'db_table': 'card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(db_column='driver_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('d_email', models.CharField(db_column='D_Email', max_length=50, unique=True)),
                ('gender', models.CharField(db_column='Gender', max_length=6)),
                ('date_of_birth', models.DateField()),
                ('license_no', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(db_column='Feedback_ID', primary_key=True, serialize=False)),
                ('message', models.CharField(db_column='Message', max_length=500)),
                ('rating', models.IntegerField(db_column='Rating')),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(db_column='passenger_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(db_column='Gender', max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'passenger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(db_column='payment_ID', primary_key=True, serialize=False)),
                ('payment_time', models.DateTimeField(db_column='Payment_time')),
                ('fare', models.FloatField(blank=True, db_column='Fare', null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'p_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='query2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(unique=True)),
                ('passenger_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Fare', models.IntegerField()),
            ],
        ),
    ]
